wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n
  central_auth_host: https://meta.wikimedia.org

session:
  type: 'ext:memcached'
  url: '127.0.0.1:11211'
  data_dir: './cache'


wsgi:
  host: labels.wmflabs.org
  application_root: ""
  url_prefix: ""
  scheme: 'https'
  cors_allowed: https://([^\.\/]+\.)?(wiki([pm]edia|data|books|versity|quote|source|news|voyage)|wiktionary|mediawiki)\.org

database:
  host: wikilabels-database-02.wikilabels.eqiad1.wikimedia.cloud
  dbname: u_wikilabels

oauth:
  mw_uri: https://meta.wikimedia.org/w/index.php
  creds: oauth-wikimedia.yaml
